CREATE TABLE sportzplatform.country
(
    country_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    country_name character varying(50) COLLATE pg_catalog."default",
    country_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    currency_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT country_pkey PRIMARY KEY (country_id)
)

TABLESPACE pg_default;

ALTER TABLE sportzplatform.country
    OWNER to postgres;

GRANT ALL ON TABLE sportzplatform.country TO postgres;

GRANT DELETE, UPDATE, INSERT, SELECT ON TABLE sportzplatform.country TO sportzplatform_user;



CREATE TABLE sportzplatform.state
(
    state_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    state_name character varying(50) COLLATE pg_catalog."default",
    statecode character varying(50) COLLATE pg_catalog."default" NOT NULL,
    country_id integer NOT NULL,
    CONSTRAINT state_pkey PRIMARY KEY (state_id),
    CONSTRAINT fk_state_country FOREIGN KEY (country_id)
        REFERENCES sportzplatform.country (country_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE sportzplatform.state
    OWNER to postgres;

GRANT ALL ON TABLE sportzplatform.state TO postgres;

GRANT DELETE, UPDATE, INSERT, SELECT ON TABLE sportzplatform.state TO sportzplatform_user;